# 1. List Formatting
MD004:
  style: dash         # Enforces using '-' for unordered lists.
MD007:
  indent: 4           # Force 4-space indentation for proper rendering.
MD032: true           # Requires blank lines above and below lists.
MD060:
  style: padded       # Controls table pipe spacing.

# 2. Style Consistency
MD046: false          # Disable checks on code block style (to support Admonitions).
MD049:
  style: asterisk     # Enforces _italics_ using asterisks.

# 3. Flexibility
MD013: false          # Disables the 80-character line length limit.
MD024:
  siblings_only: true # Allows duplicate headings under different parent heading.
MD028: false          # Allows blank lines inside blockquotes.
MD033: false          # Disables the "No Inline HTML" rule.
MD036: false          # Disables the "Emphasis used instead of a heading" rule.
MD041: false          # Disables the requirement that the first line must be an H1 header.
MD051: false          # Disables checks on link fragments (as single topics may reference each other).

# 4. Cleanup
MD009: true           # Flags trailing spaces at the end of lines.