name: Cleanup Branch Docs

on:
  delete:
    branches-ignore:
      - main
      - 'release-v*'

jobs:
  delete-docs:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'branch'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch Remote Assets
        uses: actions/checkout@v4
        with:
          repository: 'APTITUDE-Consortium/aptitude-eudi-wallet-specs'
          token: ${{ secrets.APTITUDE_REPO_UPDATE_PAT }}
          path: 'temp_remote_assets'
          clean: false
          sparse-checkout: |
            docs/glossary-definitions.md
            docs/media/
            docs/overrides/

      - name: Merge Assets into Local Workspace
        run: |
          mkdir -p docs/media docs/overrides
          cp -r temp_remote_assets/docs/* ./docs/
          rm -rf temp_remote_assets

      - name: Delete branch documentation
        run: |
          CLEAN_NAME=$(echo "${{ github.event.ref }}" | sed 's/\//-/g')
          VERSION_NAME="branch-${CLEAN_NAME}"
          mike delete --push "${VERSION_NAME}"