name: Publish MkDocs site

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch Remote Assets
        uses: actions/checkout@v4
        with:
          repository: 'APTITUDE-Consortium/aptitude-eudi-wallet-specs'
          token: ${{ secrets.APTITUDE_REPO_UPDATE_PAT }}
          path: 'temp_remote_assets'
          sparse-checkout: |
            docs/glossary-definitions.md
            docs/media/
            docs/overrides/

      - name: Merge Assets into Local Workspace
        run: |
          mkdir -p docs/media docs/overrides
          cp -r temp_remote_assets/docs/ ./docs/
          rm -rf temp_remote_assets

      - name: Deploy Pre-Release (from release-v* branch)
        if: startsWith(github.ref, 'refs/heads/release-v')
        run: |
          VERSION=$(echo "${GITHUB_REF_NAME}" | sed 's/release-//')
          PATH_NAME="${VERSION}-dev"
          mike deploy --push --allow-empty "$PATH_NAME"
          mike set-default --push "$PATH_NAME"

      - name: Deploy Official Release (from tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mike deploy --push --allow-empty --update-aliases ${GITHUB_REF_NAME} latest
          mike set-default --push latest

      - name: Deploy Main
        if: github.ref == 'refs/heads/main'
        run: |
          mike deploy --push --allow-empty main

      - name: Deploy Branch
        if: |
          github.ref_type == 'branch' &&
          github.ref_name != 'main' &&
          !startsWith(github.ref_name, 'release-v')
        run: |
          CLEAN_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's/\//-/g')
          mike deploy --push --allow-empty "branch-${CLEAN_NAME}"